# Generated by Django 5.1 on 2024-09-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('population_size', models.PositiveBigIntegerField()),
                ('area_km', models.FloatField()),
                ('capital_city', models.CharField(max_length=200)),
                ('flag', models.ImageField(upload_to='flag')),
                ('map', models.ImageField(upload_to='map')),
            ],
        ),
    ]
